# -*- mode: ruby -*-
# vi: set ft=ruby :

username="aascedu"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"

  config.vm.define "#{username}S" do |srv|
    srv.vm.hostname = "#{username}S"
    srv.vm.network "private_network", ip: "192.168.56.110"
    srv.vm.provider :virtualbox do |vb|
      vb.name = "#{username}S"
      vb.cpus = 4
      vb.memory = 4096
    end
    srv.vm.provision "shell", path: "scripts/install_k3s.sh"
  end
end
